before_script: "npm install --dev"

script: gulp phantomjs-test

language: node_js
node_js:
  - 0.10
  - 0.11

branches:
  only:
    - master

notifications:
  email:
    - nicolas.dutil@infocinc.com
